
name: unit-tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Run Tests
      run: docker run -v $(pwd):/app --rm phpunit/phpunit run
